interface comentariosProps {
    id: string,
    name: string,
    entertainment: string,
    entertainmen_name: string,
    comment: string,
    views: number,
}

export const lista_comentarios: comentariosProps[] = [
    {
        id: "asknffasnlasl",
        name: "Vinícius Silveira",
        entertainment: "Filme",
        entertainmen_name: "Oppenheimer",
        comment: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
        views: 1000000,
    },
    {
        id: "asknffasnlasl",
        name: "Vinícius Silveira",
        entertainment: "Filme",
        entertainmen_name: "Oppenheimer",
        comment: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
        views: 1000000,
    },
    {
        id: "asknffasnlasl",
        name: "Vinícius Silveira",
        entertainment: "Filme",
        entertainmen_name: "Oppenheimer",
        comment: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
        views: 1000000,
    },
    {
        id: "asknffasnlasl",
        name: "Vinícius Silveira",
        entertainment: "Filme",
        entertainmen_name: "Oppenheimer",
        comment: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
        views: 1000000,
    },
    {
        id: "asknffasnlasl",
        name: "Vinícius Silveira",
        entertainment: "Filme",
        entertainmen_name: "Oppenheimer",
        comment: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
        views: 1000000,
    },
    {
        id: "asknffasnlasl",
        name: "Vinícius Silveira",
        entertainment: "Filme",
        entertainmen_name: "Oppenheimer",
        comment: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
        views: 1000000,
    },
    {
        id: "asknffasnlasl",
        name: "Vinícius Silveira",
        entertainment: "Filme",
        entertainmen_name: "Oppenheimer",
        comment: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
        views: 1000000,
    },
    {
        id: "asknffasnlasl",
        name: "Vinícius Silveira",
        entertainment: "Filme",
        entertainmen_name: "Oppenheimer",
        comment: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
        views: 1000000,
    },
    {
        id: "asknffasnlasl",
        name: "Vinícius Silveira",
        entertainment: "Filme",
        entertainmen_name: "Oppenheimer",
        comment: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
        views: 1000000,
    },
    {
        id: "asknffasnlasl",
        name: "Vinícius Silveira",
        entertainment: "Filme",
        entertainmen_name: "Oppenheimer",
        comment: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
        views: 1000000,
    },
    {
        id: "asknffasnlasl",
        name: "Vinícius Silveira",
        entertainment: "Filme",
        entertainmen_name: "Oppenheimer",
        comment: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
        views: 1000000,
    },
    {
        id: "asknffasnlasl",
        name: "Vinícius Silveira",
        entertainment: "Filme",
        entertainmen_name: "Oppenheimer",
        comment: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
        views: 1000000,
    },
    {
        id: "asknffasnlasl",
        name: "Vinícius Silveira",
        entertainment: "Filme",
        entertainmen_name: "Oppenheimer",
        comment: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
        views: 1000000,
    },
    {
        id: "asknffasnlasl",
        name: "Vinícius Silveira",
        entertainment: "Filme",
        entertainmen_name: "Oppenheimer",
        comment: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
        views: 1000000,
    },
    {
        id: "asknffasnlasl",
        name: "Vinícius Silveira",
        entertainment: "Filme",
        entertainmen_name: "Oppenheimer",
        comment: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
        views: 1000000,
    },
    {
        id: "asknffasnlasl",
        name: "Vinícius Silveira",
        entertainment: "Filme",
        entertainmen_name: "Oppenheimer",
        comment: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
        views: 1000000,
    },
    {
        id: "asknffasnlasl",
        name: "Vinícius Silveira",
        entertainment: "Filme",
        entertainmen_name: "Oppenheimer",
        comment: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
        views: 1000000,
    },
    {
        id: "asknffasnlasl",
        name: "Vinícius Silveira",
        entertainment: "Filme",
        entertainmen_name: "Oppenheimer",
        comment: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
        views: 1000000,
    },
]